### ISSUE TITLE
add config for adding tarball name to comments

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-BumpVersionAfterRelease#12]
This feature is IMHO awful, especially since it's unconditionally added:

     - The tarball name is added as a comment to files munged during
       build so the source is more evident (in case the module name
       bears no relation to the tarball name).

What was the rationale for this?  It reminds me of
https://metacpan.org/pod/Dist::Zilla::Plugin::OurDist.
Can its use at least be made optional?

**Comment by dagolden** [comment]
Patch welcome.
