### ISSUE TITLE
Regression: Loose versions without underscores now forbidden

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Dist-Zilla-Plugin-BumpVersionAfterRelease#13]
In addition to banning decimal versions *with*  underscore, loose decimal version *without* underscores are also prohibited.

Before 0.010, `0.8.0` was a legal value in `our $VERSION`.

Now:

```
0.8.0 is not a valid version string (maybe you need 'allow_decimal_underscore')
```

I have no intent on ever using decimal underscores, and there is no decimal underscore in this version string.

**Comment by dagolden** [comment]
I'll take a patch to add an option "allow_unsafe_version_tuples" if you insist on that behavior.

I see no reason to encourage "0.8.0" over "v0.8.0" in the default settings.

**Comment by karenetheridge** [comment]
Perhaps the error message should simply be fixed, to not mention 'allow_decimal_underscore' when it's not relevant.
