### ISSUE TITLE
[BumpVersionAfterRelease]: # TRIAL comment is added based on current release, not the next one

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-BumpVersionAfterRelease#5]
From looking at `rewrite_version()`, it appears that the is_trial status of the current (just-released) release is used to determine whether to add a a `# TRIAL` comment to the `$VERSION` declaration -- which of course may not be accurate for the next release.

There are a few options that I can think of:

- allow the user to specify somehow (config option? flag? overridable method?) whether the *next* release is anticipated to be a trial (this is at least possible with the Moose dist, as the trial status is directly determined as a function of the version number itself - so I'd implement this by subclassing the plugin and adding a `is_next_release_trial` sub;
- give up on adding `# TRIAL` comments entirely, and let the user add them manually as applicable;
- have a separate pre-release munging pass that adds the `# TRIAL` comments if `is_trial`.

**Comment by dagolden** [comment]
I think this is moot now that we don't write #TRIAL
to the repo.
